### ISSUE TITLE
Error, if chunk size exceeds max buffer size

### ISSUE THREAD

**Issue by konstantinkrassmann** [vekexasia/streamsplit#1]
As the title says, if my sql file contains a data split block, which is about 1gb, then the buffer won't be able to pass it as the callback,. 

Errormessage: 

```
RangeError: Invalid typed array length
    at new Uint8Array (native)
    at createBuffer (buffer.js:25:17)
    at allocate (buffer.js:96:12)
    at new Buffer (buffer.js:56:12)
    at AnonymousObserver._onNext (C:\Users\konstantin.krassmann\Desktop\sql\recover.js:33:26)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.next (C:\Users\konstantin.krassmann\Desktop\sql\node_modules\streamsplit\node_modules\rx\dist\rx.js:1828:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\konstantin.krassmann\Desktop\sql\node_modules\streamsplit\node_modules\rx\dist\rx.js:1762:31)
    at AnonymousObserver.tryCatcher (C:\Users\konstantin.krassmann\Desktop\sql\node_modules\streamsplit\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\konstantin.krassmann\Desktop\sql\node_modules\streamsplit\node_modules\rx\dist\rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\konstantin.krassmann\Desktop\sql\node_modules\streamsplit\node_modules\rx\dist\rx.js:1762:31)
```

**Comment by vekexasia** [comment]
Is this mysqlsplit bug or dumpsplit?

Il 11 ott 2016 7:07 AM, "Konstantin Krassmann" notifications@github.com
ha scritto:

**Comment by konstantinkrassmann** [comment]
Hi there, 

So there are different type of issues. 

`toString` error caused by the limitation of maximum sized strings. 

The one error `toString` fails, because the chunk is too big to make the `chunk.toString("utf8")` work. 
This problem is located at mysqldumpsplit. I've made a workaround by adding parameters to `toString` to have some kind of substring behaviour, since i don't need to search through the whole chunk. 

`chunk.toString("utf8",0,50)` did solve the one problem for me. 

Then the other error: 

Error due to limitation of buffer sizes. 

Appears if the streamsplit finds a really big block to split and will crash when it is trying to put this block into an buffer.

**Comment by vekexasia** [comment]
Are you able to fix also the other issue

Il 12 ott 2016 7:28 AM, "Konstantin Krassmann" notifications@github.com
ha scritto:

Hi there,

So there are different type of issues.

The one error toString fails, because the chunk is too big to make the
chunk.toString("utf8") working.
This problem is located at mysqldumpsplit. I've made a workaround by adding
parameters to toString to have some kind of substring behaviour, since i
don't need to search through the whole chunk.

chunk.toString("utf8",0,50) did solve the one problem for me.

Then the other error:
Appears if the streamsplit found a really big block to split and crashes
when it is trying to put this block into an buffer.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
https://github.com/vekexasia/streamsplit/issues/1#issuecomment-253210410,
or mute the thread

**Comment by konstantinkrassmann** [comment]
Well, the other issue is more difficult to resolve.
To resolve the issue, the streamsplitter has to calculate the size of the split textblock, so the chunk of the text.  
If the size is greater then the maximum buffer size, it has to fill out multiple buffers and pass them to the subscribe as an array of buffers. 
I didn't dive deeper into the streamsplitters code, so i can't take this on me

**Comment by vekexasia** [comment]
Hello,
Thanks for your details.  I'll fix it as soon as I get back from my
vacation.

Il 13 ott 2016 11:44 PM, "Konstantin Krassmann" notifications@github.com
ha scritto:
